sudo: false

language: php
php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1

cache:
    directories:
        - $HOME/.composer/cache
        - vendor

before_install: phpenv config-rm xdebug.ini

install: composer install

notifications:
    slack:
        secure: 4TGNk8IRoNd/27ZMp96IVilZffcnO8RjOgWxUx+cedRJEykRnZAk2cziEj7u+voKZeSVB1M/zWIwe7qKAGp+8p+EH2XYUINz1qjQbNUEHrlJlCiwkoC/FfeJblPkUoJ71gDOSQvuTlR/rL7ZbPWA6YdkwmqdsY0jqgMwVHbaSJamaeq6aLZK+mRyEP+GSrxEfM6nWgRW0sXCXzjH4xdIiUXnyFtUuh1Cw+G+Ku6IaVh8Gs11rsxnu3I05LNj1PmHc+1R46iVtYVUE6Yu3nX0Qxhi7YLUcKVfGvjILxqDeAzw8ET+O2129RHCNDBJqDWINuOd553XoWharoPnJVyV3/6d4JSEaxd/X7L4BvRVwrSkhMe4httK0c8t3UVeR0xIDNnGgduCMp7fA5EZ6p71vYFQqb17TWNN7n7XZCiIBiHxUMCNAckphcnDEAlb+Y9gUFVTsjW+8RJlYB8K6cmDeqnsC//zFlYUotUusfZIRG0UoeHx9F1cRaUAs6aF4cARnPFne1FarEi1Zh/GSGYNbHJEDBNXe3lnL3u269t+q25w9aYTr06Bu4oXc7ecgqyPZB876sk8n5lI/6oeuH+Zx7oeIQwX/7teTmuUXTX4Zin+GN77NFSrTCKoIoUwHfB4s0RqiA9d3j9CVyXXuj7x9QcsB1Hx8xfSsJvQTnKwZJ4=
